import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Links } from "./links";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <Links />
          {children}
        </div>
      </body>
    </html>
  );
}